//! This required header was automatically generated by `diesel print-schema`.
//!
//! Before creating this `setup` and `migrate` your tables.
table! {
    links (id) {
        id -> Integer,
        link -> Text,
        title -> Text,
        date_created -> Text,
    }
}
